// desktop.ts — one isolated desktop per "hand".
//
// Each hand is a nested `sway` compositor started with the Wayland backend from
// inside the user's session (Hyprland on Omarchy). It shows up as an ordinary
// window, has its own seat, runs the user's real apps as the user, and only
// sees input we inject through `wlrctl` / `wtype` against its own socket.
//
//   startHand(1)            spawn nested sway, learn its WAYLAND_DISPLAY
//   screenshot(hand)        PNG bytes via grim
//   click / typeText / ...  input via wlr-virtual-pointer + virtual-keyboard
//   launch / launchBrowser  run an app inside the hand
//   stopHand / listHands    lifecycle + registry in $XDG_RUNTIME_DIR/hands
//
// CLI: bun desktop.ts up [n] | down | ls | shot <id> [file] | click <id> x y
//      | move <id> x y | scroll <id> x y dy | type <id> text | key <id> combo
//      | run <id> cmd...
//
// Requires: sway grim wtype wlrctl   (pacman -S sway grim wtype wlrctl)

import { mkdir, readdir, rm, cp } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";

// ---------------------------------------------------------------- types

export type Hand = {
  id: number;
  /** pid of the nested sway process. Hyprland reports it on the window. */
  pid: number;
  /** nested Wayland socket name, e.g. "wayland-1" */
  display: string;
  width: number;
  height: number;
};

export type ExecResult = { exitCode: number; stdout: Uint8Array; stderr: string };
export type Exec = (argv: string[], opts?: { env?: Record<string, string> }) => Promise<ExecResult>;

export type MouseButton = "left" | "right" | "middle";

// ---------------------------------------------------------------- config

const RUNTIME_DIR = process.env.XDG_RUNTIME_DIR ?? `/run/user/${process.getuid?.() ?? 1000}`;
/** Registry of running hands. One JSON file per hand. */
export const HANDS_DIR = join(RUNTIME_DIR, "hands");
/** Per-hand browser profiles (copies of the user's, so logins carry over). */
export const PROFILES_DIR = join(homedir(), ".hands");

const START_TIMEOUT_MS = 10_000;
const PACKAGE_FOR_BINARY: Record<string, string> = {
  sway: "sway",
  grim: "grim",
  wtype: "wtype",
  wlrctl: "wlrctl",
};

// ---------------------------------------------------------------- exec seam

/** Runs a command and collects its output. Tests replace this with a fake. */
export const defaultExec: Exec = async (argv, opts) => {
  let proc: ReturnType<typeof Bun.spawn>;
  try {
    proc = Bun.spawn(argv, {
      env: { ...process.env, ...opts?.env },
      stdin: "ignore",
      stdout: "pipe",
      stderr: "pipe",
    });
  } catch (err) {
    throw missingBinary(argv[0]!, err);
  }
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout as ReadableStream).bytes(),
    new Response(proc.stderr as ReadableStream).text(),
    proc.exited,
  ]);
  return { exitCode, stdout, stderr };
};

function missingBinary(bin: string, err: unknown): Error {
  const pkg = PACKAGE_FOR_BINARY[bin];
  if (pkg && !Bun.which(bin)) {
    return new Error(`"${bin}" is not installed. Install it with: sudo pacman -S ${pkg}`);
  }
  return err instanceof Error ? err : new Error(String(err));
}

async function run(exec: Exec, argv: string[], env?: Record<string, string>): Promise<ExecResult> {
  const res = await exec(argv, { env });
  if (res.exitCode !== 0) {
    throw new Error(`${argv.join(" ")} failed (exit ${res.exitCode}): ${res.stderr.trim()}`);
  }
  return res;
}

function handEnv(hand: Hand): Record<string, string> {
  return { WAYLAND_DISPLAY: hand.display };
}

// ---------------------------------------------------------------- lifecycle

/** The sway config a hand boots with. Exported for tests. */
export function swayConfig(opts: { width: number; height: number; displayFile: string }): string {
  return [
    `# generated by hands/desktop.ts`,
    `output * mode ${opts.width}x${opts.height}`,
    `default_border none`,
    `focus_follows_mouse yes`,
    `# Tell the outer world which Wayland socket this hand listens on.`,
    `exec sh -c 'echo "$WAYLAND_DISPLAY" > ${shellQuote(opts.displayFile)}'`,
    ``,
  ].join("\n");
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function registryPath(id: number) {
  return join(HANDS_DIR, `hand-${id}.json`);
}

/**
 * Start a nested desktop for hand `id`. Resolves once the nested compositor
 * has reported its socket name, so the returned Hand is immediately usable.
 */
export async function startHand(
  id: number,
  opts: { width?: number; height?: number; env?: Record<string, string> } = {},
): Promise<Hand> {
  const width = opts.width ?? 1280;
  const height = opts.height ?? 800;
  await mkdir(HANDS_DIR, { recursive: true });

  const existing = await getHand(id);
  if (existing) throw new Error(`hand ${id} is already running (pid ${existing.pid})`);

  const displayFile = join(HANDS_DIR, `hand-${id}.display`);
  const confFile = join(HANDS_DIR, `hand-${id}.conf`);
  const logFile = join(HANDS_DIR, `hand-${id}.log`);
  await rm(displayFile, { force: true });
  await Bun.write(confFile, swayConfig({ width, height, displayFile }));

  if (!Bun.which("sway")) throw missingBinary("sway", new Error("sway not found"));
  const proc = Bun.spawn(["sway", "-c", confFile], {
    env: {
      ...process.env,
      WLR_BACKENDS: "wayland", // run as a window inside the outer compositor
      WLR_WL_OUTPUTS: "1",
      ...opts.env,
    },
    stdin: "ignore",
    stdout: Bun.file(logFile),
    stderr: Bun.file(logFile),
  });
  proc.unref(); // let the CLI exit while the hand keeps running

  const deadline = Date.now() + START_TIMEOUT_MS;
  let display = "";
  while (Date.now() < deadline) {
    if (proc.exitCode !== null) break;
    const f = Bun.file(displayFile);
    if (await f.exists()) {
      display = (await f.text()).trim();
      if (display) break;
    }
    await Bun.sleep(100);
  }
  if (!display) {
    proc.kill();
    const log = (await Bun.file(logFile).exists()) ? await Bun.file(logFile).text() : "";
    throw new Error(`hand ${id}: nested sway did not come up within ${START_TIMEOUT_MS}ms\n${log.slice(-800)}`);
  }

  const hand: Hand = { id, pid: proc.pid, display, width, height };
  await Bun.write(registryPath(id), JSON.stringify(hand));
  return hand;
}

/** Kill a hand's compositor (and everything running inside it). */
export async function stopHand(hand: Hand): Promise<void> {
  try {
    process.kill(hand.pid, "SIGTERM");
  } catch {
    // already gone
  }
  await rm(registryPath(hand.id), { force: true });
  await rm(join(HANDS_DIR, `hand-${hand.id}.display`), { force: true });
}

function isAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

/** Running hands, sorted by id. Prunes registry entries whose process died. */
export async function listHands(): Promise<Hand[]> {
  let names: string[];
  try {
    names = await readdir(HANDS_DIR);
  } catch {
    return [];
  }
  const hands: Hand[] = [];
  for (const name of names) {
    if (!/^hand-\d+\.json$/.test(name)) continue;
    const hand = (await Bun.file(join(HANDS_DIR, name)).json()) as Hand;
    if (isAlive(hand.pid)) hands.push(hand);
    else await rm(join(HANDS_DIR, name), { force: true });
  }
  return hands.sort((a, b) => a.id - b.id);
}

export async function getHand(id: number): Promise<Hand | null> {
  return (await listHands()).find((h) => h.id === id) ?? null;
}

// ---------------------------------------------------------------- perception

/** PNG screenshot of the hand's whole desktop. `scale` < 1 shrinks it. */
export async function screenshot(
  hand: Hand,
  opts: { scale?: number } = {},
  exec: Exec = defaultExec,
): Promise<Uint8Array> {
  const argv = ["grim"];
  if (opts.scale && opts.scale !== 1) argv.push("-s", String(opts.scale));
  argv.push("-t", "png", "-");
  const res = await run(exec, argv, handEnv(hand));
  return res.stdout;
}

// ---------------------------------------------------------------- input

/**
 * Move the hand's cursor to absolute (x, y). `wlrctl pointer move` is relative,
 * so we first slam the cursor into the top-left corner (wlroots clamps to the
 * output) and then move by (x, y). The nested compositor has exactly one
 * output, which makes this exact.
 */
export async function moveMouse(hand: Hand, x: number, y: number, exec: Exec = defaultExec): Promise<void> {
  const env = handEnv(hand);
  await run(exec, ["wlrctl", "pointer", "move", "-100000", "-100000"], env);
  await run(exec, ["wlrctl", "pointer", "move", String(Math.round(x)), String(Math.round(y))], env);
}

export async function click(
  hand: Hand,
  x: number,
  y: number,
  opts: { button?: MouseButton; count?: number } = {},
  exec: Exec = defaultExec,
): Promise<void> {
  await moveMouse(hand, x, y, exec);
  const count = opts.count ?? 1;
  for (let i = 0; i < count; i++) {
    await run(exec, ["wlrctl", "pointer", "click", opts.button ?? "left"], handEnv(hand));
  }
}

/** Scroll at (x, y). Positive `dy` scrolls down, like a mouse wheel. */
export async function scroll(
  hand: Hand,
  x: number,
  y: number,
  dy: number,
  dx = 0,
  exec: Exec = defaultExec,
): Promise<void> {
  await moveMouse(hand, x, y, exec);
  await run(exec, ["wlrctl", "pointer", "scroll", String(dy), String(dx)], handEnv(hand));
}

/**
 * Delay before the first key event. A freshly created virtual keyboard can
 * race the compositor applying its keymap, which garbles the first
 * characters (seen once in testing). A short pause avoids it.
 */
const KEYMAP_SETTLE_MS = "40";

/** Type literal text into whatever is focused inside the hand. */
export async function typeText(hand: Hand, text: string, exec: Exec = defaultExec): Promise<void> {
  if (!text) return;
  await run(exec, ["wtype", "-s", KEYMAP_SETTLE_MS, "-d", "8", text], handEnv(hand));
}

const MODIFIERS: Record<string, string> = {
  ctrl: "ctrl",
  control: "ctrl",
  shift: "shift",
  alt: "alt",
  super: "logo",
  meta: "logo",
  cmd: "logo",
  win: "win",
  altgr: "altgr",
};

const KEY_NAMES: Record<string, string> = {
  enter: "Return",
  return: "Return",
  esc: "Escape",
  escape: "Escape",
  tab: "Tab",
  space: "space",
  backspace: "BackSpace",
  delete: "Delete",
  del: "Delete",
  up: "Up",
  down: "Down",
  left: "Left",
  right: "Right",
  home: "Home",
  end: "End",
  pageup: "Prior",
  pagedown: "Next",
  insert: "Insert",
};

/** Turn "ctrl+shift+t" into wtype arguments. Exported for tests. */
export function keyComboToWtypeArgs(combo: string): string[] {
  const parts = combo
    .split("+")
    .map((p) => p.trim())
    .filter(Boolean);
  if (parts.length === 0) throw new Error("empty key combo");
  const key = parts.pop()!;
  const mods = parts.map((m) => {
    const mod = MODIFIERS[m.toLowerCase()];
    if (!mod) throw new Error(`unknown modifier "${m}" in "${combo}"`);
    return mod;
  });
  const keyName = KEY_NAMES[key.toLowerCase()] ?? (key.length === 1 ? key : key[0]!.toUpperCase() + key.slice(1));
  const args: string[] = [];
  for (const m of mods) args.push("-M", m);
  args.push("-k", keyName);
  for (const m of [...mods].reverse()) args.push("-m", m);
  return args;
}

/** Press a key or chord, e.g. "Return", "ctrl+l", "ctrl+shift+t". */
export async function pressKey(hand: Hand, combo: string, exec: Exec = defaultExec): Promise<void> {
  await run(exec, ["wtype", "-s", KEYMAP_SETTLE_MS, ...keyComboToWtypeArgs(combo)], handEnv(hand));
}

// ---------------------------------------------------------------- apps

/** Environment that makes toolkits pick the hand's Wayland socket. */
export function appEnv(hand: Hand, extra: Record<string, string> = {}): Record<string, string> {
  const env: Record<string, string> = { ...(process.env as Record<string, string>) };
  delete env.DISPLAY; // no X here; force Wayland
  delete env.SWAYSOCK;
  delete env.I3SOCK;
  return {
    ...env,
    WAYLAND_DISPLAY: hand.display,
    XDG_SESSION_TYPE: "wayland",
    GDK_BACKEND: "wayland",
    QT_QPA_PLATFORM: "wayland",
    SDL_VIDEODRIVER: "wayland",
    MOZ_ENABLE_WAYLAND: "1",
    ELECTRON_OZONE_PLATFORM_HINT: "wayland",
    ...extra,
  };
}

/** Launch a program inside the hand. Returns its pid. */
export function launch(hand: Hand, argv: string[], env: Record<string, string> = {}): number {
  const proc = Bun.spawn(argv, {
    env: appEnv(hand, env),
    stdin: "ignore",
    stdout: "ignore",
    stderr: "ignore",
  });
  proc.unref();
  return proc.pid;
}

/**
 * Launch a browser inside the hand with its own profile directory. On first
 * use the user's real profile is copied so cookies and logins carry over.
 */
export async function launchBrowser(
  hand: Hand,
  url = "about:blank",
  opts: { copyProfile?: boolean; browser?: string } = {},
): Promise<number> {
  const copyProfile = opts.copyProfile ?? true;
  const bin =
    opts.browser ??
    ["chromium", "chromium-browser", "google-chrome-stable", "google-chrome", "brave", "firefox"].find((b) =>
      Bun.which(b),
    );
  if (!bin) throw new Error("no browser found (looked for chromium, chrome, brave, firefox)");

  if (bin.startsWith("firefox")) {
    const profile = join(PROFILES_DIR, `firefox-${hand.id}`);
    if (copyProfile && !(await exists(profile))) {
      const src = await defaultFirefoxProfile();
      if (src) await cp(src, profile, { recursive: true });
    }
    await mkdir(profile, { recursive: true });
    for (const lock of ["lock", ".parentlock"]) await rm(join(profile, lock), { force: true });
    return launch(hand, [bin, "--new-instance", "--profile", profile, url]);
  }

  const profile = join(PROFILES_DIR, `${bin}-${hand.id}`);
  if (copyProfile && !(await exists(profile))) {
    const src = chromiumProfileDir(bin);
    if (src && (await exists(src))) await cp(src, profile, { recursive: true });
  }
  await mkdir(profile, { recursive: true });
  for (const lock of ["SingletonLock", "SingletonSocket", "SingletonCookie"]) {
    await rm(join(profile, lock), { force: true });
  }
  return launch(hand, [
    bin,
    "--ozone-platform=wayland",
    `--user-data-dir=${profile}`,
    "--no-first-run",
    "--no-default-browser-check",
    "--new-window",
    url,
  ]);
}

function chromiumProfileDir(bin: string): string | null {
  const cfg = process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config");
  if (bin.includes("chromium")) return join(cfg, "chromium");
  if (bin.includes("chrome")) return join(cfg, "google-chrome");
  if (bin.includes("brave")) return join(cfg, "BraveSoftware", "Brave-Browser");
  return null;
}

async function defaultFirefoxProfile(): Promise<string | null> {
  const root = join(homedir(), ".mozilla", "firefox");
  let names: string[];
  try {
    names = await readdir(root);
  } catch {
    return null;
  }
  const pick = names.find((n) => n.endsWith(".default-release")) ?? names.find((n) => n.endsWith(".default"));
  return pick ? join(root, pick) : null;
}

async function exists(path: string): Promise<boolean> {
  try {
    await readdir(path);
    return true;
  } catch {
    return await Bun.file(path).exists();
  }
}

// ---------------------------------------------------------------- CLI

async function main(argv: string[]) {
  const [cmd, ...rest] = argv;
  const need = async (idStr: string | undefined): Promise<Hand> => {
    const id = Number(idStr);
    const hand = Number.isInteger(id) ? await getHand(id) : null;
    if (!hand) throw new Error(`no running hand with id "${idStr}". Try: bun desktop.ts ls`);
    return hand;
  };

  switch (cmd) {
    case "up": {
      const n = Number(rest.find((a) => /^\d+$/.test(a)) ?? 2);
      const terminal = rest.includes("--terminal");
      const noApp = rest.includes("--empty");
      const url = rest.find((a) => a.startsWith("--url="))?.slice(6) ?? "about:blank";
      for (let id = 1; id <= n; id++) {
        const hand = await startHand(id);
        if (terminal) launch(hand, [Bun.which("foot") ? "foot" : "alacritty"]);
        else if (!noApp) await launchBrowser(hand, url);
        console.log(`hand ${id}: pid ${hand.pid} display ${hand.display} ${hand.width}x${hand.height}`);
      }
      return;
    }
    case "down": {
      for (const hand of await listHands()) {
        await stopHand(hand);
        console.log(`stopped hand ${hand.id}`);
      }
      return;
    }
    case "ls": {
      for (const hand of await listHands()) console.log(JSON.stringify(hand));
      return;
    }
    case "shot": {
      const hand = await need(rest[0]);
      const png = await screenshot(hand);
      if (rest[1]) {
        await Bun.write(rest[1], png);
        console.log(`wrote ${rest[1]} (${png.byteLength} bytes)`);
      } else {
        await Bun.write(Bun.stdout, png);
      }
      return;
    }
    case "move": {
      await moveMouse(await need(rest[0]), Number(rest[1]), Number(rest[2]));
      return;
    }
    case "click": {
      await click(await need(rest[0]), Number(rest[1]), Number(rest[2]), {
        button: (rest[3] as MouseButton) ?? "left",
      });
      return;
    }
    case "scroll": {
      await scroll(await need(rest[0]), Number(rest[1]), Number(rest[2]), Number(rest[3] ?? 3));
      return;
    }
    case "type": {
      await typeText(await need(rest[0]), rest.slice(1).join(" "));
      return;
    }
    case "key": {
      await pressKey(await need(rest[0]), rest[1] ?? "Return");
      return;
    }
    case "run": {
      const hand = await need(rest[0]);
      const pid = launch(hand, rest.slice(1));
      console.log(`pid ${pid}`);
      return;
    }
    default:
      console.log(
        [
          "usage: bun desktop.ts <command>",
          "  up [n] [--url=URL] [--terminal] [--empty]   start n hands (default 2) with a browser each",
          "  down                                          stop all hands",
          "  ls                                            list running hands",
          "  shot <id> [file.png]                          screenshot (stdout if no file)",
          "  move <id> <x> <y>",
          "  click <id> <x> <y> [left|right|middle]",
          "  scroll <id> <x> <y> [dy]",
          "  type <id> <text...>",
          "  key <id> <combo>                              e.g. Return, ctrl+l, ctrl+shift+t",
          "  run <id> <cmd...>                             launch a program inside the hand",
        ].join("\n"),
      );
  }
}

if (import.meta.main) {
  main(process.argv.slice(2)).catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
